[package]
name = "moonstone-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oblivion = { path = "./oblivion" }
migration = { path = "migration" }
entity = { path = "entity" }

tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sea-orm = { version = "0.12", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
argon2 = { version = "0.5" }
rand = "0.8"
thiserror = "1"
regex = "1"
lazy_static = "1"
chrono = "0.4"
redis = { version = "0.24.0", features = ["tokio-rustls-comp", "json"] }
