//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::account::Entity as Account;
pub use super::community::Entity as Community;
pub use super::message::Entity as Message;
pub use super::permission::Entity as Permission;
pub use super::session::Entity as Session;
